apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: skaffold-example
    context: .
    docker:
      network: "container:alpine"
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s-*
