apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold
    docker:
      dockerfile: deploy/skaffold/Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy/skaffold/*
