apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
    - image: gcr.io/k8s-skaffold/skaffold-example-2
      context: dir
  kaniko:
    buildContext:
      localDir: {}
    pullSecretName: e2esecret
    namespace: default
    cache: {}
    flags:
      - --single-snapshot
deploy:
  kubectl:
    manifests:
      - k8s-*
