apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
  kaniko:
    buildContext: 
      localDir: {}
    pullSecretName: e2esecret
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
