apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-bazel
    workspace: .
    bazel:
      target: //:skaffold_example.tar
  local: {}
deploy:
  kubectl:
    manifests:
