apiVersion: skaffold/v1beta16
kind: Config
build:
  # only build and deploy "world-service" on main profile
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-world
    context: world-service
deploy:
  kubectl:
    manifests:
      - 'world-service/*.yaml'

profiles:
  - name: minikube-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
    build:
      # only build and deploy "hello-service" on minikube profile
      artifacts:
        - image: gcr.io/k8s-skaffold/skaffold-hello
          context: hello-service
    deploy:
      kubectl:
        manifests:
          - 'hello-service/*.yaml'

  - name: staging-profile
    build:
      # build and deploy both services on "staging"
      artifacts:
        - image: gcr.io/k8s-skaffold/skaffold-hello
          context: hello-service
        - image: gcr.io/k8s-skaffold/skaffold-world
          context: world-service
    deploy:
      # use context "staging" for staging-profile
      kubeContext: staging
      kubectl:
        manifests:
          - '**/*.yaml'
