applications:
- name: go-guestbook
  context: testdata/go-guestbook
  dev:
    command: cp testdata/backend/main.go src/backend/main.go
  labels:
    app: go-guestbook
- name: nodejs-guestbook
  context: testdata/nodejs-guestbook
  dev:
    command: cp testdata/backend/app.js src/backend/app.js
  labels:
    app: nodejs-guestbook
