apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: gcr.io/k8s-skaffold/skaffold-example
  kaniko:
    buildContext: 
      localDir: true
    pullSecretName: e2esecret
    namespace: default
deploy:
  kubectl:
    manifests:
      - k8s-*
