apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .
deploy:
  kubectl:
    manifests:
      - k8s-*
