apiVersion: batch/v1
kind: Job
metadata:
  name: test-dev-job
spec:
  template:
    spec:
      containers:
      - name: test-dev-job
        image: gcr.io/k8s-skaffold/test-dev-job
      restartPolicy: OnFailure
