apiVersion: skaffold/v1beta15
kind: Config
build:
  googleCloudBuild:
    projectId: k8s-skaffold
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
