apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
      docker:
        noCache: true
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
      docker:
         noCache: true
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
profiles:
- name: buildpacks
  build:
    artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
      custom:
        buildCommand: ../build.sh
        dependencies:
          paths:
            - .
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
      custom:
        buildCommand: ../build.sh
        dependencies:
          paths:
            - .
- name: compose
  deploy: 
    dockerCompose: {}
