apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-web
      context: ./leeroy-web/
      # docker:
      #   noCache: true
      custom:
        buildCommand: ../build.sh
        dependencies:
          paths:
            - .
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
      # docker:
      #    noCache: true
      custom:
        buildCommand: ../build.sh
        dependencies:
          paths:
            - .
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
