apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/leeroy-app
      context: ./leeroy-app/
deploy:
  kubectl:
    manifests:
      - ./leeroy-web/kubernetes/*
      - ./leeroy-app/kubernetes/*
portForward:
  - resource: deploy
    resourceName: leeroy-web
    port: 8080
