apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-jib
    # jibMaven: {}
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
