# apiVersion: v1
# kind: Pod
# metadata:
#   name: node
# spec:
#   containers:
#   - name: node
#     image: gcr.io/k8s-skaffold/node-example
#     ports:
#     - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: node-example
  labels:
    app: node-example
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: node-example
  selector:
    app: node-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-example
  labels:
    app: node-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
        - name: node-example
          image: gcr.io/k8s-skaffold/node-example
          ports:
            - containerPort: 3000
